name: Readme Assets

on:
  push:
    branches:
      - main
    paths-ignore:
      - "profile-summary-card-output/**"
  schedule:
    - cron: "14 13 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  summary-cards:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GHRS_PAT }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
          UTC_OFFSET: 2
          AUTO_PUSH: false
      - name: Postprocess summary cards
        run: node scripts/postprocess-summary-cards.mjs 2077
      - name: Commit postprocessed summary cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A profile-summary-card-output
          git diff --staged --quiet && exit 0
          git commit -m "Postprocess summary cards"
          git push
